from django.urls import path
from . import views

urlpatterns = [
    path('', views.login_view, name='login'),
    path('admin-schedule/', views.index, name='admin_schedule'),
    path('admin-schedule/<int:year>/<int:week>/', views.index, name='admin_schedule_week'),
    path('employee-tasks/', views.employee_tasks, name='employee_tasks'),
    path('employee-tasks/<int:year>/<int:week>/', views.employee_tasks, name='employee_tasks_week'),
    path('employee-schedule/', views.employee_tasks, name='employee_schedule'),
    path('employee-schedule/<int:year>/<int:week>/', views.employee_tasks, name='employee_schedule_week'),
    path('toggle-completion/<int:block_id>/', views.toggle_completion, name='toggle_completion'),
    path('update-duration/<int:block_id>/', views.update_duration, name='update_duration'),
    path('admin-statistics/', views.admin_statistics, name='admin_statistics'),
    path('admin-statistics/<int:year>/<int:month>/', views.admin_statistics, name='admin_statistics_month'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('api/employees/', views.api_employees, name='api_employees'),
    path('api/work-block/<int:block_id>/assignments/', views.api_work_block_assignments, name='api_work_block_assignments'),
    path('api/work-block/assign-employees/', views.api_assign_employees, name='api_assign_employees'),
    path('api/work-block/<int:block_id>/delete/', views.api_delete_work_block, name='api_delete_work_block'),
    path('api/work-block/<int:block_id>/toggle-archive/', views.api_toggle_archive_work_block, name='api_toggle_archive_work_block'),
    path('api/work-block/<int:block_id>/edit/', views.api_edit_work_block, name='api_edit_work_block'),
    path('api/work-block/<int:block_id>/details/', views.api_get_work_block_details, name='api_get_work_block_details'),
    path('api/bonus-penalty/add/', views.api_add_bonus_penalty, name='api_add_bonus_penalty'),
    path('api/employee/<int:employee_id>/bonuses-penalties/', views.api_get_employee_bonuses_penalties, name='api_get_employee_bonuses_penalties'),
    path('api/bonus-penalty/<int:bonus_penalty_id>/delete/', views.api_delete_bonus_penalty, name='api_delete_bonus_penalty'),
    path('api/assignment/<int:assignment_id>/toggle-payment/', views.api_toggle_assignment_payment, name='api_toggle_assignment_payment'),
    path('api/assignment/<int:assignment_id>/update-hourly-rate/', views.api_update_assignment_hourly_rate, name='api_update_assignment_hourly_rate'),
    path('api/changelogs/', views.api_get_changelogs, name='api_get_changelogs'),
    path('api/changelog/<int:changelog_id>/mark-seen/', views.api_mark_changelog_seen, name='api_mark_changelog_seen'),
    path('api/changelogs/mark-all-seen/', views.api_mark_all_changelogs_seen, name='api_mark_all_changelogs_seen'),
    path('api/changelogs/check-done/', views.api_check_changelogs_done, name='api_check_changelogs_done'),
]
