# Generated by Django 5.2.4 on 2025-07-15 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('localization', models.CharField(blank=True, default='', max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day_of_month', models.IntegerField()),
                ('month', models.IntegerField(default=7)),
                ('year', models.IntegerField(default=2025)),
                ('archived', models.BooleanField(default=False)),
                ('duration', models.FloatField(help_text='Duration in hours')),
                ('constant', models.BooleanField(default=False, help_text='If true, repeats on same weekday for the month')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.client')),
                ('employees_assigned', models.ManyToManyField(blank=True, related_name='assigned_blocks', to='gestao.employee')),
                ('employees_concluded', models.ManyToManyField(blank=True, related_name='concluded_blocks', to='gestao.employee')),
            ],
        ),
    ]
