# Generated by Django 5.2.4 on 2025-07-16 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.FloatField(help_text='Duration in hours for this employee')),
                ('is_completed', models.BooleanField(default=False)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.employee')),
                ('work_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.workblock')),
            ],
            options={
                'unique_together': {('employee', 'work_block')},
            },
        ),
    ]
