# Generated by Django 5.2.4 on 2025-01-13 20:44

from django.db import migrations


def migrate_assignments_to_new_model(apps, schema_editor):
    WorkBlock = apps.get_model('gestao', 'WorkBlock')
    Employee = apps.get_model('gestao', 'Employee')
    EmployeeWorkAssignment = apps.get_model('gestao', 'EmployeeWorkAssignment')

    # Migrate existing assignments to the new model
    for work_block in WorkBlock.objects.all():
        # Create assignments for assigned employees
        for employee in work_block.employees_assigned.all():
            EmployeeWorkAssignment.objects.get_or_create(
                employee=employee,
                work_block=work_block,
                defaults={
                    'duration': work_block.duration,
                    'is_completed': False
                }
            )

        # Mark completed assignments
        for employee in work_block.employees_concluded.all():
            assignment, created = EmployeeWorkAssignment.objects.get_or_create(
                employee=employee,
                work_block=work_block,
                defaults={
                    'duration': work_block.duration,
                    'is_completed': True
                }
            )
            if not created:
                assignment.is_completed = True
                assignment.save()


def reverse_migrate_assignments(apps, schema_editor):
    WorkBlock = apps.get_model('gestao', 'WorkBlock')
    Employee = apps.get_model('gestao', 'Employee')
    EmployeeWorkAssignment = apps.get_model('gestao', 'EmployeeWorkAssignment')

    # Restore the old many-to-many relationships
    for assignment in EmployeeWorkAssignment.objects.all():
        assignment.work_block.employees_assigned.add(assignment.employee)
        if assignment.is_completed:
            assignment.work_block.employees_concluded.add(assignment.employee)


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_add_employee_work_assignment'),
    ]

    operations = [
        migrations.RunPython(
            migrate_assignments_to_new_model,
            reverse_migrate_assignments
        ),
    ]
