# Generated by Django 5.2.4 on 2025-01-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_migrate_to_assignment_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workblock',
            name='employees_concluded',
        ),
    ]
