# Generated by Django 5.2.4 on 2025-07-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_remove_employees_concluded'),
    ]

    operations = [
        migrations.AddField(
            model_name='workblock',
            name='hourly_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Value per hour for this work block', max_digits=10),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='duration',
            field=models.FloatField(help_text='Default duration in hours'),
        ),
    ]
