# Generated by Django 5.2.4 on 2025-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_add_hourly_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours for this employee', max_digits=5),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Default duration in hours', max_digits=5),
        ),

    ]
