# Generated by Django 5.2.4 on 2025-07-24 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0006_convert_to_decimal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in euros', max_digits=10)),
                ('justification', models.TextField(help_text='Reason for bonus or penalty')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_penalties', to='gestao.employee')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
