# Generated by Django 5.2.4 on 2025-07-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0008_add_contract_and_payment_toggle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workblock',
            name='employees_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_blocks', through='gestao.EmployeeWorkAssignment', to='gestao.employee'),
        ),
    ]
