# Generated by Django 5.2.4 on 2025-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_alter_workblock_employees_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworkassignment',
            name='hourly_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override hourly rate for this specific assignment', max_digits=10, null=True),
        ),
    ]
