# Generated by Django 5.2.4 on 2025-08-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_add_hourly_rate_override'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workblock',
            name='month',
            field=models.IntegerField(default=8),
        ),
    ]
