# Generated by Django 5.2.4 on 2025-08-16 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_alter_workblock_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuspenalty',
            options={'ordering': ['-created_date'], 'verbose_name': 'Bónus ou Penalização', 'verbose_name_plural': 'Bónus ou Penalizações'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Empregado', 'verbose_name_plural': 'Empregados'},
        ),
        migrations.AlterModelOptions(
            name='workblock',
            options={'verbose_name': 'Bloco de Trabalho', 'verbose_name_plural': 'Blocos de Trabalho'},
        ),
    ]
