# Generated by Django 5.2.4 on 2025-08-16 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_alter_bonuspenalty_options_alter_client_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspenalty',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor a adicionar/subtrair do TOTAL do mês', max_digits=10, verbose_name='Quantia'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Sancionador'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus_penalties', to='gestao.employee', verbose_name='Empregado'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='justification',
            field=models.TextField(help_text='Justificação para o bónus/penalização', verbose_name='Justificação'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='month',
            field=models.IntegerField(verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='type',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='bonuspenalty',
            name='year',
            field=models.IntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='(CONTRATO) Valor hora aplicado a todos os serviços. Deixar vazio SE o empregado não estiver em contrato. NOTA: Se não estiver em contrato o valor terá que ser atribuído manualmente por bloco de trabalho criado!!!', max_digits=10, null=True, verbose_name='Valor/Hora do contrato'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Nome de utilizador das credenciais criadas para o empregado em questão.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome de utilizador'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de atribuição'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última marcação de concluído'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duration in hours for this employee', max_digits=5, verbose_name='Duração (Que poderá ser alterada)'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.employee', verbose_name='Empregado'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='hourly_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se o empregado não estiver sujeito a contrato, este valor será aquele respetivo ao pagamento pelo trabalho feito no bloco. Deixar VAZIO nos empregados por contrato. NOTA: Se porventura um empregado por contrato tiver que receber um valor/hora diferente por este serviço, colocar um valor irá sobrepor o valor do contrato para este bloco (incluindo blocos criados pela opção CONSTANTE estar ativada aquando da criação do bloco de trabalho. Isto se o valor estiver a ser definido no menu de blocos de trabalho)', max_digits=10, null=True, verbose_name='Valor/Hora a receber para o serviço atribuído'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Completou?'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='receives_payment',
            field=models.BooleanField(default=True, help_text='Desativar caso o empregado não possa receber por este bloco', verbose_name='Recebe pagamento?'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='work_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestao.workblock', verbose_name='Bloco de trabalho'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado?'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='constant',
            field=models.BooleanField(default=False, help_text='Com esta opção ativada, a tarefa será replicada no mesmo dia da semana em todas as semanas até ao final do mês selecionado.', verbose_name='Constante?'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='day_of_month',
            field=models.IntegerField(verbose_name='Dia do mês'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='duration',
            field=models.DecimalField(decimal_places=2, help_text='Duração do serviço em valores decimais. Fórmula para converter tempos (H:M) em tempos decimais: HORAS + (MINUTOS / 60)', max_digits=5, verbose_name='Duração'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='employees_assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned_blocks', through='gestao.EmployeeWorkAssignment', to='gestao.employee', verbose_name='Empregados atribuídos'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='end_time',
            field=models.TimeField(verbose_name='Hora de fim'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='hourly_value',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Valor à hora a cobrar ao cliente', max_digits=10, verbose_name='Valor/Hora'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='localization',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Morada'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='month',
            field=models.IntegerField(default=8, verbose_name='Mês'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='workblock',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Ano'),
        ),
    ]
