# Generated by Django 5.2.4 on 2025-08-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_alter_bonuspenalty_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='NOTA: Não pode existir o mesmo nome 2 vezes na base de dados!', max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employeeworkassignment',
            name='hourly_rate_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Se o empregado não estiver sujeito a contrato, este valor será aquele respetivo ao pagamento pelo trabalho feito no bloco. Deixar VAZIO nos empregados por contrato. NOTA: Se porventura um empregado por contrato tiver que receber um valor/hora diferente por este serviço, colocar um valor irá sobrepor o valor do contrato para este bloco (incluindo blocos criados pela opção CONSTANTE estar ativada aquando da criação do bloco de trabalho. Isto se o valor estiver a ser definido no menu de blocos de trabalho).', max_digits=10, null=True, verbose_name='Valor/Hora a receber para o serviço atribuído'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_name'),
        ),
    ]
