# Generated by Django 5.2.4 on 2025-08-17 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_alter_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Data de adição')),
                ('priority', models.IntegerField(default=0, verbose_name='Prioridade')),
                ('users_seen', models.ManyToManyField(blank=True, related_name='changelogs_seen', to=settings.AUTH_USER_MODEL, verbose_name='Utilizadores que viram')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
